### ISSUE TITLE
pytest -k gives AttributeError: 'Function' object has no attribute 'when'

### ISSUE THREAD

**Issue by hugovk** [skudriashev/pytest-timer#3]
There's an error when using `pytest -k` to select a single test.

# pytest + pytest-timer

```console
$ pytest day09/part2.py
================================================= test session starts ==================================================
platform darwin -- Python 3.9.1, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
rootdir: /Users/hugo/github/advent-of-code/2020
plugins: requests-mock-1.8.0, random-order-1.0.4, rerunfailures-9.1.1, flaky-3.7.0, hypothesis-5.41.3, xdist-2.1.0, timer-0.0.8, cov-2.10.1, testmon-1.0.3, forked-1.3.0
collected 2 items

day09/part2.py ..                                                                                                [100%]

===================================================== pytest-timer =====================================================
[success] 61.51% day09/part2.py::test2[35\n20\n15\n25\n47\n40\n62\n55\n65\n95\n102\n117\n150\n182\n127\n219\n299\n277\n309\n576-5-62]: 0.0005s
[success] 38.49% day09/part2.py::test[35\n20\n15\n25\n47\n40\n62\n55\n65\n95\n102\n117\n150\n182\n127\n219\n299\n277\n309\n576-5-127]: 0.0003s
================================================== 2 passed in 0.07s ===================================================
```

# pytest -k (no pytest-timer)

```console
$ pytest day09/part2.py -k test2
================================================= test session starts ==================================================
platform darwin -- Python 3.9.1, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
rootdir: /Users/hugo/github/advent-of-code/2020
plugins: requests-mock-1.8.0, random-order-1.0.4, rerunfailures-9.1.1, flaky-3.7.0, hypothesis-5.41.3, xdist-2.1.0, cov-2.10.1, testmon-1.0.3, forked-1.3.0
collected 2 items / 1 deselected / 1 selected

day09/part2.py .                                                                                                 [100%]

=========================================== 1 passed, 1 deselected in 0.09s ============================================
```

# pytest -k + pytest-timer

```console
$ pytest day09/part2.py -k test2
================================================= test session starts ==================================================
platform darwin -- Python 3.9.1, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
rootdir: /Users/hugo/github/advent-of-code/2020
plugins: requests-mock-1.8.0, random-order-1.0.4, rerunfailures-9.1.1, flaky-3.7.0, hypothesis-5.41.3, xdist-2.1.0, timer-0.0.8, cov-2.10.1, testmon-1.0.3, forked-1.3.0
collected 2 items / 1 deselected / 1 selected

day09/part2.py .                                                                                                 [100%]

===================================================== pytest-timer =====================================================
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 164, in main
    ret = config.hook.pytest_cmdline_main(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_pytest/main.py", line 306, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_pytest/main.py", line 294, in wrap_session
    config.hook.pytest_sessionfinish(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_pytest/terminal.py", line 804, in pytest_sessionfinish
    self.config.hook.pytest_terminal_summary(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytest_timer/plugin.py", line 98, in pytest_terminal_summary
    for rep in (r for r in reports if r.when == "call"):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytest_timer/plugin.py", line 98, in <genexpr>
    for rep in (r for r in reports if r.when == "call"):
AttributeError: 'Function' object has no attribute 'when'
```

**Comment by skudriashev** [comment]
@hugovk thanks for reporting. Will have a look 👍
